"""delete conclusion in triage_code

Revision ID: 20e98af07241
Revises: f66c79cee41f
Create Date: 2024-08-08 07:41:31.963597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e98af07241'
down_revision = 'f66c79cee41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.drop_column('triage_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triage_code', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
