"""database nullable models changed

Revision ID: 741bed006cbd
Revises: 10ceb414dbde
Create Date: 2024-08-08 16:42:58.853632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '741bed006cbd'
down_revision = '10ceb414dbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('blood_pressure',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('pulse',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('respiratory_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('temperature',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('saturation',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('triaj',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('triaj',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('saturation',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('respiratory_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('pulse',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('blood_pressure',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
