"""User is_blocked.

Revision ID: 9b1ee6d7e5f5
Revises: bfeb215f0d94
Create Date: 2024-07-05 14:20:04.502768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1ee6d7e5f5'
down_revision = 'bfeb215f0d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
