"""patient add protokol, triaj

Revision ID: bfeb215f0d94
Revises: 981a12e9100a
Create Date: 2024-07-05 00:18:42.999977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfeb215f0d94'
down_revision = '981a12e9100a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protokol', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('triaj', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('triaj')
        batch_op.drop_column('protokol')

    # ### end Alembic commands ###
