"""Update migration

Revision ID: f66c79cee41f
Revises: 9b1ee6d7e5f5
Create Date: 2024-08-08 07:37:13.495463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66c79cee41f'
down_revision = '9b1ee6d7e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_coming', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('service_coming')

    # ### end Alembic commands ###
